import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import background from "../assets/background.jpg";
import SvgComponent from "../components/logo";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={"relative min-h-screen pl-36 py-16 pr-60"}>
      <Image
        src={background}
        layout="fill"
        objectFit="cover"
        objectPosition="center"
        className="-z-10"
      />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
      <nav className="text-white flex items-center">
        <SvgComponent width={50} height={50} />
        <h2 className="text-2xl ml-3 tracking-[.5em] mr-auto">TEMPO</h2>
        <ul className="flex flex-row items-center space-x-12 text-[1.3rem]">
          <li>
            <a href="#">Marketplace</a>
          </li>
          <li>
            <a href="#">Noticias</a>
          </li>
          <li>
            <a href="#">Servicios</a>
          </li>
          <li>
            <a href="#">Musica</a>
          </li>
          <li>
            <button className="bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 py-[.8rem] px-4 w-44 rounded-[4rem]">
              Inicio
            </button>
          </li>
        </ul>
      </nav>

      <main className={""}></main>

      <footer className={""}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
