import type { NextPage } from "next";
import Image from "next/future/image";
import Head from "next/head";
import { AiFillInstagram } from "react-icons/ai";
import { BsTwitter, BsYoutube } from "react-icons/bs";
import { FaDiscord } from "react-icons/fa";
import background from "../assets/background.jpg";
import SvgComponent from "../components/logo";
const Home: NextPage = () => {
  return (
    <>
      <Image src={background} className="-z-10 absolute" alt="background" />
      <div className={"relative min-h-screen pl-36 py-16 pr-60"}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div></div>
        <nav className="text-white flex items-center">
          <SvgComponent width={50} height={50} />
          <h2 className="text-2xl ml-3 tracking-[.5em] mr-auto">TEMPO</h2>
          <ul className="flex flex-row items-center space-x-12 text-[1.3rem]">
            <li className="cursor-pointer">
              <a href="#">Marketplace</a>
            </li>
            <li>
              <a href="#">Noticias</a>
            </li>
            <li>
              <a href="#">Servicios</a>
            </li>
            <li>
              <a href="#">Musica</a>
            </li>
            <li>
              <button className="bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 py-[.8rem] px-4 w-44 rounded-[4rem]">
                Inicio
              </button>
            </li>
          </ul>
        </nav>

        <main className={""}></main>

        <footer
          className={
            "flex items-center justify-evenly w-full fixed bottom-0  pb-8 pr-60"
          }
        >
          <div className=" flex space-x-8">
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <FaDiscord className="text-[1.5rem] text-white" />
            </a>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <BsTwitter className="text-[1.5rem] text-white" />
            </a>

            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillInstagram className="text-[1.5rem] text-white" />
            </a>

            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <BsYoutube className="text-[1.5rem] text-white" />
            </a>
          </div>
          <p className="text-white flex-1 text-center capitalize">
            &copy; &#160; 2022 RITMOS RECORDS. all Right Reserved
          </p>
        </footer>
      </div>
    </>
  );
};

export default Home;
